# Generated by Django 5.0 on 2024-01-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManagement', '0002_alter_attendance_details_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pin_code',
            field=models.IntegerField(default=1234),
        ),
        migrations.CreateModel(
            name='Security_Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('fp_status', models.CharField(max_length=100)),
                ('pin_status', models.CharField(max_length=100)),
                ('lock_status', models.CharField(max_length=100)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
    ]
