# Generated by Django 5.0 on 2024-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_details',
            name='in_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance_details',
            name='out_time',
            field=models.TimeField(null=True),
        ),
    ]
