# Generated by Django 5.0 on 2024-01-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManagement', '0003_employee_pin_code_security_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='topic_id',
        ),
        migrations.RemoveField(
            model_name='job_title',
            name='dep_id',
        ),
        migrations.RemoveField(
            model_name='duty_duration',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='duty_duration',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='attendance_details',
            name='out_time',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pin_code',
        ),
        migrations.CreateModel(
            name='Face_Data',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('face', models.ImageField(blank=True, null=True, upload_to='')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprint_Data',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('fp', models.ImageField(upload_to='')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Pin_Data',
            fields=[
                ('pin_id', models.AutoField(primary_key=True, serialize=False)),
                ('pin_code', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Duty_Duration',
        ),
        migrations.DeleteModel(
            name='Job_Title',
        ),
    ]
