# Generated by Django 5.0 on 2024-01-16 16:14

import attendanceManagement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendanceManagement', '0004_remove_department_topic_id_remove_job_title_dep_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='face_data',
            name='face',
            field=models.ImageField(blank=True, null=True, upload_to=attendanceManagement.models.upload_faces_to),
        ),
        migrations.AlterField(
            model_name='fingerprint_data',
            name='fp',
            field=models.ImageField(blank=True, null=True, upload_to=attendanceManagement.models.upload_fp_to),
        ),
        migrations.AlterField(
            model_name='pin_data',
            name='pin_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendanceManagement.topic'),
        ),
    ]
